from fpdf import FPDF
import hashlib
import json
import datetime
import os

class WipeCertificate(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'ZeroTrace - Data Destruction Certificate', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, 'Generated by ZeroTrace Tool', 0, 0, 'C')

def generate_certificate(drive_info, method, status, output_path="certificate.pdf", verified=True):
    pdf = WipeCertificate()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    METHOD_DESCRIPTIONS = {
        "NIST 800-88 Clear": "NIST SP 800-88 Clear (Single-pass overwrite with all zeros 0x00)",
        "NIST 800-88-2 Purge": "NIST SP 800-88-2 Purge (Single-pass overwrite with random data)",
        "DoD 5220.22-M (3-Pass)": "DoD 5220.22-M 3-Pass (Pass 1: Zeros, Pass 2: Ones, Pass 3: Random)",
        "DoD 5220.22-M ECE (7-Pass)": "DoD 5220.22-M ECE 7-Pass (Alternating characters and random passes)",
        "Peter Gutmann (35-Pass)": "Peter Gutmann 35-Pass (35 passes of alternating and random overwrite sequences)"
    }
    
    method_desc = METHOD_DESCRIPTIONS.get(method, f"Secure Overwrite ({method})")
    verification_text = "Random Sector Spot Check Passed" if verified else "Verification Failed / Incomplete"
    
    content = [
        f"Certificate ID: {hashlib.sha256(timestamp.encode()).hexdigest()[:16]}",
        f"Date: {timestamp}",
        f"Status: {status}",
        "",
        "Drive Information:",
        f"  Model: {drive_info.get('model') or drive_info.get('Model') or 'Unknown'}",
        f"  Serial Number: {drive_info.get('serial') or drive_info.get('SerialNumber') or 'Unknown'}",
        f"  Size: {drive_info.get('size') or drive_info.get('Size') or 'Unknown'}",
        "",
        "Wipe Method:",
        f"  Name: {method}",
        f"  Description: {method_desc}",
        f"  Verification: {verification_text}",
        "",
        "Digital Signature:",
    ]
    
    content_str = "".join(content)
    signature = hashlib.sha256(content_str.encode()).hexdigest()
    content.append(signature)
    
    for line in content:
        pdf.cell(0, 10, line, 0, 1)
        
    pdf.output(output_path)
    
    json_data = {
        "timestamp": timestamp,
        "drive": drive_info,
        "method": method,
        "status": status,
        "verified": verified,
        "signature": signature
    }
    
    with open(output_path.replace(".pdf", ".json"), "w") as f:
        json.dump(json_data, f, indent=4)
        
    return output_path
